type: "transformation"
version: "1.0"
pipeline:
  components:
    Populate Fixed Flow:
      type: "fixed-flow"
      parameters:
        componentName: "Populate Fixed Flow"
        columns:
        - - "SOR_KEY"
          - "VARCHAR"
          - "10"
          - ""
        - - "FILE_KEY"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_NAME"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_TITLE"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_DESCRIPTION"
          - "VARCHAR"
          - "2048"
          - ""
        - - "FILE_FUNCTION"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_PREFIX"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_SUFFIX"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_EXTENSION"
          - "VARCHAR"
          - "255"
          - ""
        - - "IS_ZIP"
          - "VARCHAR"
          - "8"
          - ""
        - - "FREQUENCY"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_NAME_FORMAT"
          - "VARCHAR"
          - "255"
          - ""
        - - "FOLDER_PATH"
          - "VARCHAR"
          - "255"
          - ""
        - - "S3_BUCKET"
          - "VARCHAR"
          - "1024"
          - ""
        - - "SF_SOURCE_TABLE_NAME"
          - "VARCHAR"
          - "512"
          - ""
        - - "IS_ACTIVE"
          - "BOOLEAN"
          - ""
          - ""
        - - "EXTRA_CLEAN"
          - "VARCHAR"
          - "255"
          - ""
        - - "HISTORY_TYPE"
          - "VARCHAR"
          - "255"
          - ""
        - - "HISTORY_DATE_FIELD"
          - "VARCHAR"
          - "255"
          - ""
        - - "COMMENT"
          - "VARCHAR"
          - "1024"
          - ""
        values:
        - - "NUMERATOR"
          - "Circular_YYYYMMDD.txt"
          - "Circular"
          - "Circular"
          - "These are the list of ads from all markets where the Proximo products\
            \ are being sold"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "CIRCULAR"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "AdBlockID"
          - ""
        - - "NUMERATOR"
          - "Circular_delete_YYYYMMDD.txt"
          - "Circular_delete"
          - ""
          - "Circular Records that should be deleted from the accumulated history\
            \ prior to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "CIRCULAR_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
        - - "NUMERATOR"
          - "Store_YYYYMMDD.txt"
          - "Store"
          - "Store"
          - "List of stores where the products are sold or being advertised"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "STORE"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "AdID"
          - ""
        - - "NUMERATOR"
          - "Store_delete_YYYYMMDD.txt"
          - "Store_delete"
          - ""
          - "Store Records that should be deleted from the accumulated history prior\
            \ to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "STORE_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
        - - "NUMERATOR"
          - "UPC_YYYYMMDD.txt"
          - "UPC"
          - "UPC"
          - "List of Universal Product Codes"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "UPC"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "Top AdBlockID"
          - ""
        - - "NUMERATOR"
          - "UPC_delete_YYYYMMDD.txt"
          - "UPC_delete"
          - ""
          - "UPC Records that should be deleted from the accumulated history prior\
            \ to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "UPC_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
        - - "NUMERATOR"
          - "Confidential_Numerator_Data_for_Proximo_MMDDYYYY.zip"
          - "Confidential_Numerator_Data_for_Proximo"
          - "Confidential_Numerator"
          - " This is the ZIP file containing the Circular, Store, and UPC data files"
          - "MULTI FILE EXTRACT"
          - ""
          - "_MMDDYYYY"
          - "zip"
          - "Yes"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - ""
          - "TRUE"
          - "FALSE"
          - ""
          - ""
          - ""
    CTRL_FILE_EXTRACTS (Update):
      type: "table-update"
      sources:
      - "Populate Fixed Flow"
      parameters:
        componentName: "CTRL_FILE_EXTRACTS (Update)"
        warehouse: "[Environment Default]"
        database: "${ev_database}"
        schema: "${ev_controls_schema}"
        targetTable: "CTRL_FILE_EXTRACTS"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - |-
            "target"."SOR_KEY" = "input"."SOR_KEY"
            AND
            "target"."FILE_KEY" = "input"."FILE_KEY"
          - "Join"
        whenMatched:
        - - |-
            "target"."SOR_KEY" = "input"."SOR_KEY"
            AND
            "target"."FILE_KEY" = "input"."FILE_KEY"
          - "Update"
        updateMapping:
        - - "SOR_KEY"
          - "SOR_KEY"
        - - "FILE_KEY"
          - "FILE_KEY"
        - - "FILE_NAME"
          - "FILE_NAME"
        - - "FILE_TITLE"
          - "FILE_TITLE"
        - - "FILE_DESCRIPTION"
          - "FILE_DESCRIPTION"
        - - "FILE_FUNCTION"
          - "FILE_FUNCTION"
        - - "FILE_PREFIX"
          - "FILE_PREFIX"
        - - "FILE_SUFFIX"
          - "FILE_SUFFIX"
        - - "FILE_EXTENSION"
          - "FILE_EXTENSION"
        - - "IS_ZIP"
          - "IS_ZIP"
        - - "FREQUENCY"
          - "FREQUENCY"
        - - "FILE_NAME_FORMAT"
          - "FILE_NAME_FORMAT"
        - - "FOLDER_PATH"
          - "FOLDER_PATH"
        - - "S3_BUCKET"
          - "S3_BUCKET"
        - - "SF_SOURCE_TABLE_NAME"
          - "SF_SOURCE_TABLE_NAME"
        - - "IS_ACTIVE"
          - "IS_ACTIVE"
        - - "EXTRA_CLEAN"
          - "EXTRA_CLEAN"
        - - "HISTORY_TYPE"
          - "HISTORY_TYPE"
        - - "HISTORY_DATE_FIELD"
          - "HISTORY_DATE_FIELD"
        - - "COMMENT"
          - "COMMENT"
        includeNotMatched: "Yes"
        insertMapping:
        - - "SOR_KEY"
          - "SOR_KEY"
        - - "FILE_KEY"
          - "FILE_KEY"
        - - "FILE_NAME"
          - "FILE_NAME"
        - - "FILE_TITLE"
          - "FILE_TITLE"
        - - "FILE_DESCRIPTION"
          - "FILE_DESCRIPTION"
        - - "FILE_FUNCTION"
          - "FILE_FUNCTION"
        - - "FILE_PREFIX"
          - "FILE_PREFIX"
        - - "FILE_SUFFIX"
          - "FILE_SUFFIX"
        - - "FILE_EXTENSION"
          - "FILE_EXTENSION"
        - - "IS_ZIP"
          - "IS_ZIP"
        - - "FREQUENCY"
          - "FREQUENCY"
        - - "FILE_NAME_FORMAT"
          - "FILE_NAME_FORMAT"
        - - "FOLDER_PATH"
          - "FOLDER_PATH"
        - - "S3_BUCKET"
          - "S3_BUCKET"
        - - "SF_SOURCE_TABLE_NAME"
          - "SF_SOURCE_TABLE_NAME"
        - - "IS_ACTIVE"
          - "IS_ACTIVE"
        - - "EXTRA_CLEAN"
          - "EXTRA_CLEAN"
        - - "HISTORY_TYPE"
          - "HISTORY_TYPE"
        - - "HISTORY_DATE_FIELD"
          - "HISTORY_DATE_FIELD"
        - - "COMMENT"
          - "COMMENT"
    Populate Fixed Flow 2:
      type: "fixed-flow"
      parameters:
        componentName: "Populate Fixed Flow 2"
        columns:
        - - "SOR_KEY"
          - "VARCHAR"
          - "10"
          - ""
        - - "FILE_KEY"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_NAME"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_TITLE"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_DESCRIPTION"
          - "VARCHAR"
          - "2048"
          - ""
        - - "FILE_FUNCTION"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_PREFIX"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_SUFFIX"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_EXTENSION"
          - "VARCHAR"
          - "255"
          - ""
        - - "IS_ZIP"
          - "VARCHAR"
          - "8"
          - ""
        - - "FREQUENCY"
          - "VARCHAR"
          - "255"
          - ""
        - - "FILE_NAME_FORMAT"
          - "VARCHAR"
          - "255"
          - ""
        - - "FOLDER_PATH"
          - "VARCHAR"
          - "255"
          - ""
        - - "S3_BUCKET"
          - "VARCHAR"
          - "1024"
          - ""
        - - "SF_SOURCE_TABLE_NAME"
          - "VARCHAR"
          - "512"
          - ""
        - - "IS_ACTIVE"
          - "BOOLEAN"
          - ""
          - ""
        - - "EXTRA_CLEAN"
          - "VARCHAR"
          - "255"
          - ""
        - - "HISTORY_TYPE"
          - "VARCHAR"
          - "255"
          - ""
        - - "HISTORY_DATE_FIELD"
          - "VARCHAR"
          - "255"
          - ""
        - - "COMMENT"
          - "VARCHAR"
          - "1024"
          - ""
        values:
        - - "NUMERATOR"
          - "Circular_YYYYMMDD.txt"
          - "CIRCULAR"
          - "Circular"
          - "These are the list of ads from all markets where the Proximo products\
            \ are being sold"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "CIRCULAR"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "AdBlockID"
          - ""
        - - "NUMERATOR"
          - "Circular_delete_YYYYMMDD.txt"
          - "CIRCULAR_DELETE"
          - ""
          - "Circular Records that should be deleted from the accumulated history\
            \ prior to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "CIRCULAR_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
        - - "NUMERATOR"
          - "Store_YYYYMMDD.txt"
          - "STORE"
          - "Store"
          - "List of stores where the products are sold or being advertised"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "STORE"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "AdID"
          - ""
        - - "NUMERATOR"
          - "Store_delete_YYYYMMDD.txt"
          - "STORE_DELETE"
          - ""
          - "Store Records that should be deleted from the accumulated history prior\
            \ to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "STORE_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
        - - "NUMERATOR"
          - "UPC_YYYYMMDD.txt"
          - "UPC"
          - "UPC"
          - "List of Universal Product Codes"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "UPC"
          - "TRUE"
          - "FALSE"
          - "DELETE_FILE"
          - "Top AdBlockID"
          - ""
        - - "NUMERATOR"
          - "UPC_delete_YYYYMMDD.txt"
          - "UPC_DELETE"
          - ""
          - "UPC Records that should be deleted from the accumulated history prior\
            \ to the update with new data"
          - "SINGLE FILE EXTRACT"
          - ""
          - "_YYYYMMDD"
          - "txt"
          - "No"
          - "Weekly"
          - "{FILE_NAME}{FILE_SUFFIX}"
          - "sftp://sftp.promo.numerator.com:22/"
          - "s3://proximo-analytics-dev/NUMERATOR/[YYYY]/[MM]/[DD]/"
          - "UPC_DELETE"
          - "TRUE"
          - "FALSE"
          - "APPEND"
          - ""
          - ""
design:
  components:
    Populate Fixed Flow:
      position:
        x: 389
        "y": 177
      tempMetlId: 3112391
    CTRL_FILE_EXTRACTS (Update):
      position:
        x: 592
        "y": 176
      tempMetlId: 3112748
    Populate Fixed Flow 2:
      position:
        x: 390
        "y": 80
      tempMetlId: 3112749
  notes:
    "3112728":
      position:
        x: -4
        "y": 80
      size:
        height: 134
        width: 273
      theme: "green"
      content: |-
        1. Enter updates into gSheet
        2. Copy/Paste into Fixed Flow component
        3. Enter individual records only to update.

        NOTE: Do not update NABCA.  Adrian Fung has taken ownership of NABCA and may perform updates to control tables using Snowflake.
