type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "PRX_DEV_WILLIAM"
        - "PRX_DEV_INTEGRATION"
        - "PRX_DEV_HEMANTH"
        - "PRX_DEV_MARCUS"
      parameters:
        componentName: "Start"
    PRX_DEV_WILLIAM:
      type: "sql-executor"
      parameters:
        componentName: "PRX_DEV_WILLIAM"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "CREATE DATABASE IF NOT EXISTS PRX_DEV_WILLIAM;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    PRX_DEV_INTEGRATION:
      type: "sql-executor"
      parameters:
        componentName: "PRX_DEV_INTEGRATION"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "CREATE DATABASE IF NOT EXISTS PRX_DEV_INTEGRATION;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    PRX_DEV_HEMANTH:
      type: "sql-executor"
      parameters:
        componentName: "PRX_DEV_HEMANTH"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "CREATE DATABASE IF NOT EXISTS PRX_DEV_HEMANTH;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    PRX_DEV_MARCUS:
      type: "sql-executor"
      parameters:
        componentName: "PRX_DEV_MARCUS"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "CREATE DATABASE IF NOT EXISTS PRX_DEV_MARCUS;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -390
        "y": 40
      tempMetlId: 1
    PRX_DEV_WILLIAM:
      position:
        x: -150
        "y": 10
      tempMetlId: 2
    PRX_DEV_INTEGRATION:
      position:
        x: -150
        "y": -90
      tempMetlId: 3
    PRX_DEV_HEMANTH:
      position:
        x: -150
        "y": 120
      tempMetlId: 4
    PRX_DEV_MARCUS:
      position:
        x: -150
        "y": 240
      tempMetlId: 5
