# This file stores secrets for your Streamlit app.
# IMPORTANT: Add .streamlit/secrets.toml to your .gitignore file!

[connections.snowflake]
account = ""
user = ""
password = ""
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "DIGITAL_ASSETS"
schema = "PUBLIC"
