type: "transformation"
version: "1.0"
pipeline:
  components:
    MATILLION_TASK_HISTORY_DETAILED_RAW:
      type: "table-input"
      parameters:
        componentName: "MATILLION_TASK_HISTORY_DETAILED_RAW"
        database: "${ev_database}"
        schema: "CONTROLS"
        targetTable: "MATILLION_TASK_HISTORY_DETAILED_RAW"
        columnNames:
        - "Data Value"
        timeOffset: ""
    CALCULATOR:
      type: "calculator"
      sources:
      - "BREAK OUT JSON"
      parameters:
        componentName: "CALCULATOR"
        includeInputColumns: "Yes"
        calculations:
        - - "DATEADD(milliseconds, \"tasks-element_endTime\", '1970-01-01')"
          - "tasks-element_endTime"
        - - "DATEADD(milliseconds, \"tasks-element_startTime\", '1970-01-01')"
          - "tasks-element_startTime"
        - - "DATEADD(milliseconds, \"jobTimestamp\", '1970-01-01')"
          - "jobTimestamp"
        - - "DATEADD(milliseconds, \"completeTime\", '1970-01-01')"
          - "completeTime"
        - - "DATEADD(milliseconds,\"endTime\" , '1970-01-01')"
          - "endTime"
        - - "DATEADD(milliseconds, \"enqueuedTime\", '1970-01-01')"
          - "enqueuedTime"
        - - "DATEADD(milliseconds, \"startTime\", '1970-01-01')"
          - "startTime"
    BREAK OUT JSON:
      type: "extract-nested-data-sf"
      sources:
      - "MATILLION_TASK_HISTORY_DETAILED_RAW"
      parameters:
        componentName: "BREAK OUT JSON"
        includeInputColumns: "No"
        columns:
        - name: "completeTime"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "completeTime"
          isArray: "false"
          include: "true"
        - name: "customerID"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "customerID"
          isArray: "false"
          include: "true"
        - name: "endTime"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "endTime"
          isArray: "false"
          include: "true"
        - name: "enqueuedTime"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "enqueuedTime"
          isArray: "false"
          include: "true"
        - name: "environmentID"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "environmentID"
          isArray: "false"
          include: "true"
        - name: "environmentName"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "environmentName"
          isArray: "false"
          include: "true"
        - name: "groupName"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "groupName"
          isArray: "false"
          include: "true"
        - name: "hasHistoricJobs"
          datatype: "BOOLEAN"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "hasHistoricJobs"
          isArray: "false"
          include: "true"
        - name: "id"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "id"
          isArray: "false"
          include: "true"
        - name: "jobID"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "jobID"
          isArray: "false"
          include: "true"
        - name: "jobName"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "jobName"
          isArray: "false"
          include: "true"
        - name: "message"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "message"
          isArray: "false"
          include: "true"
        - name: "originatorID"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "originatorID"
          isArray: "false"
          include: "true"
        - name: "projectName"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "projectName"
          isArray: "false"
          include: "true"
        - name: "startTime"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "startTime"
          isArray: "false"
          include: "true"
        - name: "state"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "state"
          isArray: "false"
          include: "true"
        - name: "tasks"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "tasks"
          isArray: "true"
          include: "false"
          childElements:
          - name: "tasks-element"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "Data Value"
            aliasName: "tasks-element"
            isArray: "false"
            include: "false"
            childElements:
            - name: "componentName"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "componentName"
              isArray: "false"
              include: "true"
            - name: "endTime"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_endTime"
              isArray: "false"
              include: "true"
            - name: "jobID"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_jobID"
              isArray: "false"
              include: "true"
            - name: "jobRevision"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "jobRevision"
              isArray: "false"
              include: "true"
            - name: "jobTimestamp"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "jobTimestamp"
              isArray: "false"
              include: "true"
            - name: "startTime"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_startTime"
              isArray: "false"
              include: "true"
            - name: "taskBatchID"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "taskBatchID"
              isArray: "false"
              include: "true"
            - name: "taskID"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "taskID"
              isArray: "false"
              include: "true"
            - name: "type"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_type"
              isArray: "false"
              include: "true"
            - name: "parentID"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "parentID"
              isArray: "false"
              include: "true"
            - name: "rowCount"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_rowCount"
              isArray: "false"
              include: "true"
            - name: "state"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_state"
              isArray: "false"
              include: "true"
            - name: "componentID"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "componentID"
              isArray: "false"
              include: "true"
            - name: "message"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_message"
              isArray: "false"
              include: "true"
            - name: "completeTime"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_completeTime"
              isArray: "false"
              include: "true"
            - name: "jobName"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "Data Value"
              aliasName: "tasks-element_jobName"
              isArray: "false"
              include: "true"
        - name: "versionID"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "versionID"
          isArray: "false"
          include: "true"
        - name: "versionName"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "versionName"
          isArray: "false"
          include: "true"
        - name: "projectID"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "projectID"
          isArray: "false"
          include: "true"
        - name: "tracksCompleteTime"
          datatype: "BOOLEAN"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "tracksCompleteTime"
          isArray: "false"
          include: "true"
        - name: "rowCount"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "rowCount"
          isArray: "false"
          include: "true"
        - name: "jobNames"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "jobNames"
          isArray: "true"
          include: "false"
          childElements:
          - name: "jobNames-element"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "Data Value"
            aliasName: "jobNames-element"
            isArray: "false"
            include: "false"
        - name: "type"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "Data Value"
          aliasName: "type"
          isArray: "false"
          include: "true"
        outerJoin: "False"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    RENAME COLUMNS:
      type: "rename"
      sources:
      - "SORT DATA"
      parameters:
        componentName: "RENAME COLUMNS"
        columnMapping:
          fromGrid:
            variable: "RENAME_COLUMNS"
            columns:
            - "Old"
            - "New"
        includeInputColumns: "No"
    SORT DATA:
      type: "rank"
      sources:
      - "FILTER FOR SCHEDULES ONLY"
      parameters:
        componentName: "SORT DATA"
        includeInputColumns: "Yes"
        partitionData:
        orderingWithinPartitions:
        - - "taskID"
          - "Asc"
        - - "componentID"
          - "Asc"
        - - "taskBatchID"
          - "Asc"
        functions:
        - - "Row Number"
          - "Remove"
    FILTER FOR SCHEDULES ONLY:
      type: "filter"
      sources:
      - "CALCULATOR"
      parameters:
        componentName: "FILTER FOR SCHEDULES ONLY"
        filterConditions:
        - - "type"
          - "Is"
          - "Equal to"
          - "SCHEDULE_ORCHESTRATION"
        combineCondition: "AND"
    CURRENT_TIMESTAMP:
      type: "calculator"
      sources:
      - "RENAME COLUMNS"
      parameters:
        componentName: "CURRENT_TIMESTAMP"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "TIMESTAMP"
    MATILLION_TASK_HISTORY_DETAILED_CLEAN:
      type: "table-output"
      sources:
      - "CURRENT_TIMESTAMP"
      parameters:
        componentName: "MATILLION_TASK_HISTORY_DETAILED_CLEAN"
        warehouse: "[Environment Default]"
        database: "${ev_database}"
        schema: "CONTROLS"
        targetTable: "MATILLION_TASK_HISTORY_DETAILED_CLEAN"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "COMPLETE_TIME"
          - "COMPLETE_TIME"
        - - "COMPONENT_ID"
          - "COMPONENT_ID"
        - - "COMPONENT_NAME"
          - "COMPONENT_NAME"
        - - "CUSTOMER_ID"
          - "CUSTOMER_ID"
        - - "END_TIME"
          - "END_TIME"
        - - "ENQUEUED_TIME"
          - "ENQUEUED_TIME"
        - - "ENVIRONMENT_ID"
          - "ENVIRONMENT_ID"
        - - "ENVIRONMENT_NAME"
          - "ENVIRONMENT_NAME"
        - - "GROUP_NAME"
          - "GROUP_NAME"
        - - "HAS_HISTORIC_JOBS"
          - "HAS_HISTORIC_JOBS"
        - - "ID"
          - "ID"
        - - "JOB_ID"
          - "JOB_ID"
        - - "JOB_NAME"
          - "JOB_NAME"
        - - "JOB_REVISION"
          - "JOB_REVISION"
        - - "JOB_TIMESTAMP"
          - "JOB_TIMESTAMP"
        - - "MESSAGE"
          - "MESSAGE"
        - - "ORIGINATOR_ID"
          - "ORIGINATOR_ID"
        - - "PARENT_ID"
          - "PARENT_ID"
        - - "PROJECT_ID"
          - "PROJECT_ID"
        - - "PROJECT_NAME"
          - "PROJECT_NAME"
        - - "ROW_COUNT"
          - "ROW_COUNT"
        - - "START_TIME"
          - "START_TIME"
        - - "STATE"
          - "STATE"
        - - "TASK_BATCH_ID"
          - "TASK_BATCH_ID"
        - - "TASK_ID"
          - "TASK_ID"
        - - "TASKS_ELEMENT_COMPLETE_TIME"
          - "TASKS_ELEMENT_COMPLETE_TIME"
        - - "TASKS_ELEMENT_END_TIME"
          - "TASKS_ELEMENT_END_TIME"
        - - "TASKS_ELEMENT_JOB_ID"
          - "TASKS_ELEMENT_JOB_ID"
        - - "TASKS_ELEMENT_JOB_NAME"
          - "TASKS_ELEMENT_JOB_NAME"
        - - "TASKS_ELEMENT_MESSAGE"
          - "TASKS_ELEMENT_MESSAGE"
        - - "TASKS_ELEMENT_ROW_COUNT"
          - "TASKS_ELEMENT_ROW_COUNT"
        - - "TASKS_ELEMENT_START_TIME"
          - "TASKS_ELEMENT_START_TIME"
        - - "TASKS_ELEMENT_STATE"
          - "TASKS_ELEMENT_STATE"
        - - "TASKS_ELEMENT_TYPE"
          - "TASKS_ELEMENT_TYPE"
        - - "TRACKS_COMPLETE_TIME"
          - "TRACKS_COMPLETE_TIME"
        - - "TYPE"
          - "TYPE"
        - - "VERSION_ID"
          - "VERSION_ID"
        - - "VERSION_NAME"
          - "VERSION_NAME"
        - - "TIMESTAMP"
          - "TIMESTAMP"
        orderBy:
        outputMode: "Append"
  variables:
    RENAME_COLUMNS:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          Old:
            columnType: "TEXT"
          New:
            columnType: "TEXT"
      defaultValue:
      - - "completeTime"
        - "COMPLETE_TIME"
      - - "componentID"
        - "COMPONENT_ID"
      - - "componentName"
        - "COMPONENT_NAME"
      - - "customerID"
        - "CUSTOMER_ID"
      - - "endTime"
        - "END_TIME"
      - - "enqueuedTime"
        - "ENQUEUED_TIME"
      - - "environmentID"
        - "ENVIRONMENT_ID"
      - - "environmentName"
        - "ENVIRONMENT_NAME"
      - - "groupName"
        - "GROUP_NAME"
      - - "hasHistoricJobs"
        - "HAS_HISTORIC_JOBS"
      - - "id"
        - "ID"
      - - "jobID"
        - "JOB_ID"
      - - "jobName"
        - "JOB_NAME"
      - - "jobRevision"
        - "JOB_REVISION"
      - - "jobTimestamp"
        - "JOB_TIMESTAMP"
      - - "message"
        - "MESSAGE"
      - - "originatorID"
        - "ORIGINATOR_ID"
      - - "parentID"
        - "PARENT_ID"
      - - "projectID"
        - "PROJECT_ID"
      - - "projectName"
        - "PROJECT_NAME"
      - - "rowCount"
        - "ROW_COUNT"
      - - "startTime"
        - "START_TIME"
      - - "state"
        - "STATE"
      - - "taskBatchID"
        - "TASK_BATCH_ID"
      - - "taskID"
        - "TASK_ID"
      - - "tasks-element_completeTime"
        - "TASKS_ELEMENT_COMPLETE_TIME"
      - - "tasks-element_endTime"
        - "TASKS_ELEMENT_END_TIME"
      - - "tasks-element_jobID"
        - "TASKS_ELEMENT_JOB_ID"
      - - "tasks-element_jobName"
        - "TASKS_ELEMENT_JOB_NAME"
      - - "tasks-element_message"
        - "TASKS_ELEMENT_MESSAGE"
      - - "tasks-element_rowCount"
        - "TASKS_ELEMENT_ROW_COUNT"
      - - "tasks-element_startTime"
        - "TASKS_ELEMENT_START_TIME"
      - - "tasks-element_state"
        - "TASKS_ELEMENT_STATE"
      - - "tasks-element_type"
        - "TASKS_ELEMENT_TYPE"
      - - "tracksCompleteTime"
        - "TRACKS_COMPLETE_TIME"
      - - "type"
        - "TYPE"
      - - "versionID"
        - "VERSION_ID"
      - - "versionName"
        - "VERSION_NAME"
design:
  components:
    MATILLION_TASK_HISTORY_DETAILED_RAW:
      position:
        x: 80
        "y": 192
      tempMetlId: 2105540
    CALCULATOR:
      position:
        x: 400
        "y": 192
      tempMetlId: 2106141
    BREAK OUT JSON:
      position:
        x: 272
        "y": 192
      tempMetlId: 2106149
    RENAME COLUMNS:
      position:
        x: 832
        "y": 192
      tempMetlId: 2106371
    SORT DATA:
      position:
        x: 688
        "y": 192
      tempMetlId: 2106477
    FILTER FOR SCHEDULES ONLY:
      position:
        x: 560
        "y": 192
      tempMetlId: 2106989
    CURRENT_TIMESTAMP:
      position:
        x: 960
        "y": 192
      tempMetlId: 2108441
    MATILLION_TASK_HISTORY_DETAILED_CLEAN:
      position:
        x: 1168
        "y": 192
      tempMetlId: 2334195
  notes:
    "2106307":
      position:
        x: 302
        "y": -20
      size:
        height: 148
        width: 319
      theme: "green"
      content: |-
        taskID - Shows the unique ID for each individual action performed in the job
        componentID - Shows the unique ID for each individual component in the job
        taskBatchID - Shows the unique ID for the job
