type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Fixed Iterator 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Fixed Iterator 0:
      type: "fixed-iterator"
      transitions:
        success:
        - "Fixed Iterator 1"
        unconditional:
        - "Create Databases"
      iterationTarget: "Create Databases"
      skipped: false
      parameters:
        componentName: "Fixed Iterator 0"
        concurrency: "Sequential"
        variablesToIterate:
        - "jv_database_name"
        iterationValues:
        - - "${ev_database}"
        breakOnFailure: "No"
    Create Databases:
      type: "sql-executor"
      skipped: false
      parameters:
        componentName: "Create Databases"
        scriptLocation: "Component"
        sqlScript: "CREATE DATABASE IF NOT EXISTS ${jv_database_name};"
    Fixed Iterator 1:
      type: "fixed-iterator"
      transitions:
        unconditional:
        - "Grants on Databases"
      iterationTarget: "Grants on Databases"
      skipped: false
      parameters:
        componentName: "Fixed Iterator 1"
        concurrency: "Sequential"
        variablesToIterate:
        - "jv_database_name"
        iterationValues:
        - - "${ev_database}"
        breakOnFailure: "No"
    Grants on Databases:
      type: "sql-executor"
      skipped: false
      parameters:
        componentName: "Grants on Databases"
        scriptLocation: "Component"
        sqlScript: |-
          USE ROLE ${ev_pseudo_admin};
          GRANT CREATE SCHEMA ON DATABASE ${jv_database_name} TO ROLE ACCOUNTADMIN;
  variables:
    jv_database_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_schema_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start 0:
      position:
        x: -30
        "y": 20
      tempMetlId: 1
    Fixed Iterator 0:
      position:
        x: 140
        "y": 0
      tempMetlId: 2
    Create Databases:
      position:
        x: 140
        "y": 0
      tempMetlId: 3
    Fixed Iterator 1:
      position:
        x: 272
        "y": 0
      tempMetlId: 4
    Grants on Databases:
      position:
        x: 470
        "y": 0
      tempMetlId: 5
