type: "orchestration"
version: "1.0"
pipeline:
  components:
    DOWNLOAD TASK HISTORY:
      type: "start"
      transitions:
        unconditional:
        - "DEFINE DATES"
      skipped: false
      parameters:
        componentName: "DOWNLOAD TASK HISTORY"
    DEFINE DATES:
      type: "query-to-scalar"
      transitions:
        success:
        - "DATE ITERATOR"
      skipped: false
      parameters:
        componentName: "DEFINE DATES"
        mode: "Advanced"
        query: "select \n'2024-04-30'  as start_date,\nCURRENT_DATE() as end_date,\n\
          DATEDIFF(day,start_date,end_date) as MaxValue\n\n      \n\n"
        scalarVariableMapping:
        - - "jv_START_DATE"
          - "START_DATE"
        - - "jv_END_DATE"
          - "END_DATE"
        - - "jv_MAX_VALUE"
          - "MAXVALUE"
    DATE ITERATOR:
      type: "loop-iterator"
      transitions:
        success:
        - "DELETE 14 DAYS OLD RECORDS FROM MATILLION_TASK_HISTORY_DETAILED_CLEAN"
      iterationTarget: "LOAD INTO SNOWFLAKE RAW"
      skipped: false
      parameters:
        componentName: "DATE ITERATOR"
        concurrency: "Sequential"
        variableToIterate: "jv_DIFF_NUMBER"
        startingValue: "0"
        incrementValue: "1"
        endValue: "${jv_MAX_VALUE}"
        breakOnFailure: "No"
    LOAD INTO SNOWFLAKE RAW:
      type: "run-orchestration"
      skipped: false
      parameters:
        componentName: "LOAD INTO SNOWFLAKE RAW"
        orchestrationJob: "00 00 Admin/00 03 Task History/00 03 05 LOAD INTO SNOWFLAKE\
          \ RAW (DETAILED)"
        setScalarVariables:
        - - "jv_DIFF_NUMBER"
          - "${jv_DIFF_NUMBER}"
        - - "jv_MAX_VALUE"
          - "${jv_MAX_VALUE}"
        - - "jv_START_DATE"
          - "${jv_START_DATE}"
        setGridVariables:
    DELETE 14 DAYS OLD RECORDS FROM MATILLION_TASK_HISTORY_DETAILED_CLEAN:
      type: "sql-script"
      skipped: false
      parameters:
        componentName: "DELETE 14 DAYS OLD RECORDS FROM MATILLION_TASK_HISTORY_DETAILED_CLEAN"
        sqlScript: |-
          DELETE FROM ${ev_database}.CONTROLS.MATILLION_TASK_HISTORY_DETAILED_CLEAN
          WHERE COMPLETE_TIME < DATEADD(days,-14,current_date())
  variables:
    jv_END_DATE:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_MAX_VALUE:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_START_DATE:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_DIFF_NUMBER:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    DOWNLOAD TASK HISTORY:
      position:
        x: -688
        "y": 0
      tempMetlId: 2104630
    DEFINE DATES:
      position:
        x: -528
        "y": 0
      tempMetlId: 2104631
    DATE ITERATOR:
      position:
        x: -368
        "y": 0
      tempMetlId: 2104632
    LOAD INTO SNOWFLAKE RAW:
      position:
        x: -368
        "y": 0
      tempMetlId: 2106615
    DELETE 14 DAYS OLD RECORDS FROM MATILLION_TASK_HISTORY_DETAILED_CLEAN:
      position:
        x: -128
        "y": 0
      tempMetlId: 2108778
  notes:
    "2104629":
      position:
        x: -741
        "y": -196
      size:
        height: 154
        width: 680
      theme: "green"
      content: "**Process: Call API to extract daily schedules detailed task history\
        \ \n\nControl:\n- ${ev_database}.CONTROLS.MATILLION_TASK_HISTORY_DETAILED_RAW\
        \ - Truncated After CLEAN\n- ${ev_database}.CONTROLS.MATILLION_TASK_HISTORY_DETAILED_CLEAN\
        \ - Daily Refresh\n\nSteps:\n1 - Define Date Range\n2 - Iterate through API\
        \ call for each day\n3 - Clean MATILLION_TASK_HISTORY_DETAILED_RAW into MATILLION_TASK_HISTORY_DETAILED_CLEAN\
        \ one day at a time"
    "2108941":
      position:
        x: -590
        "y": 84
      size:
        height: 43
        width: 135
      theme: "green"
      content: "**SCHEDULED TO EXTRACT TODAY'S LAST RUN SCHEDULE**"
    "2107058":
      position:
        x: -211
        "y": 84
      size:
        height: 40
        width: 175
      theme: "green"
      content: "**RETENTION PERIOD = 14 DAYS**"
