type: "orchestration"
version: "1.0"
pipeline:
  components:
    START:
      type: "start"
      transitions:
        unconditional:
        - "Fixed Iterator 0"
        - "TRUNCATE S3_FILE_LIST"
      skipped: false
      parameters:
        componentName: "START"
    Grid Iterator 0:
      type: "grid-iterator"
      iterationTarget: "UPDATE CTRL_LOAD_HISTORY"
      skipped: true
      parameters:
        componentName: "Grid Iterator 0"
        gridVariable: "gv_LOAD_HISTORY"
        gridIteratorVariableMapping:
        - - "SOR_KEY"
          - "jv_SOR_KEY"
        - - "FILE_KEY"
          - "jv_FILE_KEY"
        - - "FILE_PREFIX"
          - "jv_FILE_PREFIX"
        - - "FILE_NAME"
          - "jv_FILE_NAME"
        - - "FILE_SUFFIX"
          - "jv_FILE_SUFFIX"
        - - "FILE_DATE"
          - "jv_FILE_DATE"
        - - "PROCESS_STEP"
          - "jv_PROCESS_STEP"
        - - "PROCESS_END_TIME"
          - "jv_PROCESS_END_TIME"
        breakOnFailure: "No"
        concurrency: "Sequential"
    TRUNCATE S3_FILE_LIST:
      type: "sql-script"
      transitions:
        success:
        - "File Iterator 0"
      skipped: true
      parameters:
        componentName: "TRUNCATE S3_FILE_LIST"
        sqlScript: "TRUNCATE ${ev_database}.CONTROLS.S3_FILE_LIST"
    S3_FILE_LIST:
      type: "query-to-grid"
      transitions:
        success:
        - "Grid Iterator 0"
      skipped: true
      parameters:
        componentName: "S3_FILE_LIST"
        mode: "Advanced"
        query: "WITH \nS3_FILE_LIST AS (       \n                SELECT * FROM ${ev_database}.CONTROLS.S3_FILE_LIST\n\
          \                )\n,CTRL_LOAD_HISTORY AS(  \n  SELECT *,\n            \
          \                CONCAT(\n                            REPLACE(\n       \
          \                     REPLACE(\n                            REPLACE(\n \
          \                           REPLACE(\n                            REPLACE(\n\
          \                            REPLACE(\n                            REPLACE(FILE_NAME_FORMAT\n\
          \                                    ,'{FILE_NAME}',FILE_NAME)\n       \
          \                             ,'{FILE_PREFIX}',FILE_PREFIX)      \n    \
          \                                ,'{FILE_SUFFIX}',FILE_SUFFIX)\n       \
          \                             ,'{FREQUENCY}',FREQUENCY) \n             \
          \                       ,'{YYYY}',YEAR) \n                             \
          \       ,'{MM}',MONTH) \n                                    ,'{DD}',DAY)\n\
          \                                    ,'.', FILE_EXTENSION)\n           \
          \                         AS GENERATED_FILE_NAME        \n             \
          \               \n                                    \n               \
          \             FROM (\n                                        SELECT A.*,B.FILE_NAME_FORMAT,B.FILE_EXTENSION,\n\
          \                                        TO_VARCHAR(TO_DATE(A.FILE_DATE\
          \ ),'YYYY') AS YEAR,\n                                        TO_VARCHAR(TO_DATE(A.FILE_DATE\
          \ ),'MM') AS MONTH,\n                                        TO_VARCHAR(TO_DATE(A.FILE_DATE\
          \ ),'DD') AS DAY,\n                                        FROM ${ev_database}.CONTROLS.CTRL_LOAD_HISTORY\
          \ A\n                                        INNER JOIN ${ev_database}.CONTROLS.CTRL_FILE_EXTRACTS\
          \ B\n                                        ON A.FILE_KEY = B.FILE_KEY\n\
          \                                        WHERE A.SOR_KEY = 'TDLINX' \n \
          \                                       AND B.SOR_KEY = 'TDLINX'\n     \
          \                                   AND A.PROCESS_STATUS = 'FAIL'\n    \
          \                                    AND A.PROCESS_STEP = 'STAGE'\n    \
          \                                    AND A.FREQUENCY !='History'\n     \
          \                                   )\n)\n\nSELECT \nB.SOR_KEY,\nB.FILE_KEY,\n\
          B.FILE_PREFIX,\nB.FILE_NAME,\nB.FILE_SUFFIX,\nB.FREQUENCY,\nB.FILE_DATE,\n\
          B.PROCESS_STEP,\nB.PROCESS_END_TIME,\n'SUCCESS' AS PROCESS_STATUS,\n'Manually\
          \ Adjusted' as PROCESS_NOTE,\nB.ROW_COUNT,\nFROM S3_FILE_LIST A\nINNER JOIN\
          \ CTRL_LOAD_HISTORY B\nON A.FILENAME = B.GENERATED_FILE_NAME"
        gridVariable: "gv_LOAD_HISTORY"
        gridVariableMapping:
        - - "SOR_KEY"
          - "SOR_KEY"
        - - "FILE_KEY"
          - "FILE_KEY"
        - - "FILE_PREFIX"
          - "FILE_PREFIX"
        - - "FILE_NAME"
          - "FILE_NAME"
        - - "FILE_SUFFIX"
          - "FILE_SUFFIX"
        - - "FREQUENCY"
          - "FREQUENCY"
        - - "FILE_DATE"
          - "FILE_DATE"
        - - "PROCESS_STEP"
          - "PROCESS_STEP"
        - - "PROCESS_END_TIME"
          - "PROCESS_END_TIME"
        - - "PROCESS_STATUS"
          - "PROCESS_STATUS"
        - - "PROCESS_NOTE"
          - "PROCESS_NOTE"
        - - "ROW_COUNT"
          - "ROW_COUNT"
    UPDATE CTRL_LOAD_HISTORY:
      type: "sql-script"
      skipped: true
      parameters:
        componentName: "UPDATE CTRL_LOAD_HISTORY"
        sqlScript: |-
          UPDATE ${ev_database}.CONTROLS.CTRL_LOAD_HISTORY
          SET PROCESS_STATUS = 'SUCCESS', PROCESS_NOTE = 'Manually Adjusted'
          WHERE SOR_KEY = 'TDLINX'
          AND FILE_KEY = '${jv_FILE_KEY}'
          AND FILE_PREFIX = ''
          AND FILE_NAME = '${jv_FILE_NAME}'
          AND FILE_SUFFIX = '${jv_FILE_SUFFIX}'
          AND FILE_DATE = '${jv_FILE_DATE}'
          AND PROCESS_STEP = '${jv_PROCESS_STEP}'
          AND PROCESS_END_TIME = '${jv_PROCESS_END_TIME}'
          AND PROCESS_STATUS = 'FAIL'
    File Iterator 0:
      type: "file-iterator"
      transitions:
        success:
        - "S3_FILE_LIST"
      iterationTarget: "READ S3 BUCKET"
      skipped: false
      parameters:
        componentName: "File Iterator 0"
        inputDataType: "S3"
        inputDataUrl1: "s3://proximo-analytics-dev/TDLINX/2024/"
        inputDataUrl3: "Yes"
        maxIterations: "5000"
        filterRegex: ".*"
        concurrency: "Sequential"
        variables:
        - - "jv_BASE_FOLDER"
          - "Base Folder"
        - - "jv_SUBFOLDER"
          - "Subfolder"
        - - "jv_FILENAME"
          - "Filename"
        - - "jv_LAST_MODIFIED"
          - "Last Modified"
        breakOnFailure: "No"
    READ S3 BUCKET:
      type: "sql-script"
      skipped: false
      parameters:
        componentName: "READ S3 BUCKET"
        sqlScript: "INSERT INTO ${ev_database}.CONTROLS.S3_FILE_LIST (BASEFOLDER,\
          \ SUBFOLDER,FILENAME, LASTMODIFIED)\nVALUES (\n  '${jv_BASE_FOLDER}',\n\
          \  '${jv_SUBFOLDER}',\n  '${jv_FILENAME}', \n  CAST('${jv_LAST_MODIFIED}'\
          \ AS DATE)\n)\n\n\n"
    Fixed Iterator 0:
      type: "fixed-iterator"
      iterationTarget: "SQL Script 0"
      skipped: true
      parameters:
        componentName: "Fixed Iterator 0"
        concurrency: "Sequential"
        variablesToIterate:
        - "jv_FILE_DATE"
        iterationValues:
        - - "2023-01-04"
        - - "2023-01-11"
        - - "2023-01-18"
        - - "2023-01-25"
        - - "2023-03-01"
        - - "2023-03-08"
        - - "2023-03-15"
        - - "2023-03-22"
        - - "2023-03-29"
        - - "2023-04-05"
        - - "2023-04-12"
        - - "2023-04-26"
        - - "2023-05-03"
        - - "2023-05-10"
        - - "2023-05-17"
        - - "2023-05-24"
        - - "2023-05-31"
        - - "2023-06-07"
        - - "2023-06-14"
        - - "2023-06-21"
        - - "2023-06-28"
        - - "2023-07-05"
        - - "2023-07-12"
        - - "2023-07-19"
        - - "2023-07-26"
        - - "2023-08-02"
        - - "2023-08-09"
        - - "2023-08-16"
        - - "2023-08-23"
        - - "2023-08-30"
        - - "2023-09-06"
        - - "2023-09-13"
        - - "2023-09-20"
        - - "2023-09-27"
        - - "2023-10-04"
        - - "2023-10-11"
        - - "2023-10-18"
        - - "2023-10-28"
        - - "2023-11-01"
        - - "2023-11-04"
        - - "2023-11-11"
        - - "2023-11-18"
        - - "2023-11-23"
        - - "2023-12-02"
        - - "2023-12-09"
        - - "2023-12-17"
        - - "2023-12-23"
        - - "2023-12-30"
        breakOnFailure: "No"
    SQL Script 0:
      type: "sql-script"
      skipped: true
      parameters:
        componentName: "SQL Script 0"
        sqlScript: "INSERT INTO ${ev_database}.CONTROLS.CTRL_LOAD_HISTORY \n\
          \n(\n  SOR_KEY,\n  FILE_KEY,\n  FILE_NAME, \n  FILE_PREFIX,\n  FILE_SUFFIX,\
          \ \n  FREQUENCY,\n  FILE_DATE, \n  PROCESS_STEP, \n  PROCESS_END_TIME, \n\
          \  PROCESS_STATUS, \n  PROCESS_NOTE\n)\n \nVALUES \t(\n  \t\t 'TDLINX',\
          \ \n  \t\t 'PRXIMACC.CSV', \n         'PRXIMACC', \n         NULL,   \n\
          \         NULL, \n         'Weekly',\n         '${jv_FILE_DATE}', \n   \
          \      'STAGE', \n         CURRENT_TIMESTAMP, \n         'SUCCESS', \n \
          \        'Manual adjustment to logging'\n\t\t\t);"
  variables:
    jv_SOR_KEY:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILENAME:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILE_KEY:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILE_DATE:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILE_NAME:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_SUBFOLDER:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_BASE_FOLDER:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILE_PREFIX:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_FILE_SUFFIX:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_PROCESS_STEP:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_LAST_MODIFIED:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_PROCESS_END_TIME:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    gv_LOAD_HISTORY:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          SOR_KEY:
            columnType: "TEXT"
          FILE_KEY:
            columnType: "TEXT"
          FILE_PREFIX:
            columnType: "TEXT"
          FILE_NAME:
            columnType: "TEXT"
          FILE_SUFFIX:
            columnType: "TEXT"
          FREQUENCY:
            columnType: "TEXT"
          FILE_DATE:
            columnType: "TEXT"
          PROCESS_STEP:
            columnType: "TEXT"
          PROCESS_END_TIME:
            columnType: "TEXT"
          PROCESS_STATUS:
            columnType: "TEXT"
          PROCESS_NOTE:
            columnType: "TEXT"
          ROW_COUNT:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    START:
      position:
        x: -16
        "y": 0
      tempMetlId: 2547051
    Grid Iterator 0:
      position:
        x: 480
        "y": 0
      tempMetlId: 2547058
    TRUNCATE S3_FILE_LIST:
      position:
        x: 93
        "y": 1
      tempMetlId: 2547059
    S3_FILE_LIST:
      position:
        x: 336
        "y": 0
      tempMetlId: 2547060
    UPDATE CTRL_LOAD_HISTORY:
      position:
        x: 480
        "y": 32
      tempMetlId: 2547061
    File Iterator 0:
      position:
        x: 224
        "y": 0
      tempMetlId: 2547062
    READ S3 BUCKET:
      position:
        x: 224
        "y": 32
      tempMetlId: 2547063
    Fixed Iterator 0:
      position:
        x: 160
        "y": 176
      tempMetlId: 2566808
    SQL Script 0:
      position:
        x: 160
        "y": 208
      tempMetlId: 2566969
  notes:
    "2547053":
      position:
        x: -72
        "y": -189
      size:
        height: 103
        width: 621
      theme: "green"
      content: "**Process: Identify files correctly staged into S3 where the STAGE\
        \ log entry in Load_History displays the incorrect information\n\nDescription:\
        \ Using a specified S3 Bucket Path, we read the S3 Bucket and populate files\
        \ into S3_FILE_LIST snowflake table. We then read these results and update\
        \ the Load_History table to fix the incorrect information. \n**\n"
    "2567359":
      position:
        x: 59
        "y": 111
      size:
        height: 164
        width: 266
      theme: "yellow"
      content: "This inserts manual entries into CTRL_LOAD_HISTORY for a specific\
        \ file over many dates"
