type: "transformation"
version: "1.0"
pipeline:
  components:
    Fixed Flow:
      type: "fixed-flow"
      parameters:
        componentName: "Fixed Flow"
        columns:
        - - "SOR_KEY"
          - "VARCHAR"
          - "32"
          - ""
        - - "FILE_KEY"
          - "VARCHAR"
          - "255"
          - ""
        - - "PROCESS_STEP"
          - "VARCHAR"
          - "255"
          - ""
        - - "SCHEMA_NAME"
          - "VARCHAR"
          - "255"
          - ""
        - - "TABLE_NAME"
          - "VARCHAR"
          - "255"
          - ""
        - - "TEST_INDEX"
          - "NUMBER"
          - ""
          - "4"
        - - "TEST_NAME"
          - "VARCHAR"
          - "255"
          - ""
        - - "TEST_DESCRIPTION"
          - "VARCHAR"
          - "16777216"
          - ""
        - - "TEST_CATEGORY"
          - "VARCHAR"
          - "255"
          - ""
        - - "TEST_SQL_QUERY"
          - "VARCHAR"
          - "16777216"
          - ""
        - - "RESULT_TYPE"
          - "VARCHAR"
          - "50"
          - ""
        - - "RESULT_VALUE_EXPECTED"
          - "VARCHAR"
          - "16777216"
          - ""
        - - "ACTIVE_FLAG"
          - "VARCHAR"
          - ""
          - ""
        values:
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "1"
          - "Category ID Completeness"
          - "Check for NULL category IDs in product category reference table"
          - "Completeness"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.PRDC_REF WHERE CATEGORY_ID IS NULL"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "2"
          - "Product Key and UPC Uniqueness"
          - "Verify PRODUCT_KEY and UPC combinations are unique in product category\
            \ reference table"
          - "Uniqueness"
          - "SELECT COUNT(*) - COUNT(DISTINCT (PRODUCT_KEY || '_' || UPC)) FROM RAW_NIELSEN.PRDC_REF\
            \ WHERE PRODUCT_KEY IS NOT NULL AND UPC IS NOT NULL"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "3"
          - "Category Name Validity"
          - "Check that category names are not blank or only whitespace"
          - "Validity"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.PRDC_REF WHERE CATEGORY_NAME IS NULL\
            \ OR TRIM(CATEGORY_NAME) = ''"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "4"
          - "Category Update Timeliness"
          - "Check that category data has been updated within the last 180 days"
          - "Timeliness"
          - "SELECT CASE WHEN MAX(METADATA_LAST_UPDATED_DATE) > DATEADD(day, -180,\
            \ CURRENT_DATE()) THEN 0 ELSE 1 END FROM RAW_NIELSEN.PRDC_REF"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "5"
          - "Category Type Accuracy"
          - "Check that category types are within the expected set of values"
          - "Accuracy"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.PRDC_REF WHERE CATEGORY_TYPE NOT IN\
            \ ('SPIRITS', 'WINE', 'BEER', 'RTD', 'OTHER')"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_prdc_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "PRDC_REF"
          - "6"
          - "Parent Category Consistency"
          - "Check that parent category IDs reference existing categories"
          - "Consistency"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.PRDC_REF child WHERE child.PARENT_CATEGORY_ID\
            \ IS NOT NULL AND NOT EXISTS (SELECT 1 FROM RAW_NIELSEN.PRDC_REF parent\
            \ WHERE child.PARENT_CATEGORY_ID = parent.CATEGORY_ID)"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "1"
          - "Transaction ID Completeness"
          - "Check for NULL transaction IDs in fact table"
          - "Completeness"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.FCT WHERE TRANSACTION_ID IS NULL"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "2"
          - "Product ID Completeness"
          - "Check for NULL product IDs in fact table"
          - "Completeness"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.FCT WHERE PRODUCT_ID IS NULL"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "3"
          - "Transaction Record Uniqueness"
          - "Verify transaction records are unique based on transaction ID, product\
            \ ID, and date"
          - "Uniqueness"
          - "SELECT COUNT(*) - COUNT(DISTINCT (TRANSACTION_ID || '_' || PRODUCT_ID\
            \ || '_' || TRANSACTION_DATE)) FROM RAW_NIELSEN.FCT WHERE TRANSACTION_ID\
            \ IS NOT NULL AND PRODUCT_ID IS NOT NULL AND TRANSACTION_DATE IS NOT NULL"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "4"
          - "Data Timeliness"
          - "Check that data is not older than 90 days"
          - "Timeliness"
          - "SELECT CASE WHEN MAX(TRANSACTION_DATE) > DATEADD(day, -90, CURRENT_DATE())\
            \ THEN 0 ELSE 1 END FROM RAW_NIELSEN.FCT"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "5"
          - "Quantity Validity"
          - "Check that quantities are within valid range (not negative or unreasonably\
            \ large)"
          - "Validity"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.FCT WHERE QUANTITY < 0 OR QUANTITY >\
            \ 10000"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "6"
          - "Price Accuracy"
          - "Check for negative or zero prices in fact table"
          - "Accuracy"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.FCT WHERE PRICE <= 0"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "7"
          - "Sales Amount Calculation Accuracy"
          - "Check that sales amount equals price multiplied by quantity"
          - "Accuracy"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.FCT WHERE ABS(SALES_AMOUNT - (PRICE\
            \ * QUANTITY)) > 0.01 AND PRICE IS NOT NULL AND QUANTITY IS NOT NULL AND\
            \ SALES_AMOUNT IS NOT NULL"
          - "EXACT_SCALAR"
          - "0"
          - "FALSE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_fct.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "FCT"
          - "8"
          - "Fake Test to Fail"
          - "Fake test to demo failure"
          - "Testing"
          - "SELECT 1"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_mrkt_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "MRKT_REF"
          - "1"
          - "Market Key Completeness"
          - "Check for NULL market keys in market reference table"
          - "Completeness"
          - "SELECT COUNT(*) FROM RAW_NIELSEN.MRKT_REF WHERE \"Market_Key\" IS NULL"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
        - - "NIELSEN"
          - "Proximo_spirits_extract_mrkt_ref.txt.gz"
          - "LAND"
          - "RAW_NIELSEN"
          - "MRKT_REF"
          - "3"
          - "Market Key Uniqueness"
          - "Verify market keys are unique in market reference table"
          - "Uniqueness"
          - "SELECT COUNT(*) - COUNT(DISTINCT \"Market_Key\") FROM RAW_NIELSEN.MRKT_REF"
          - "EXACT_SCALAR"
          - "0"
          - "TRUE"
    CTRL_TEST_DQ_TESTS:
      type: "table-output"
      sources:
      - "Fixed Flow"
      parameters:
        componentName: "CTRL_TEST_DQ_TESTS"
        warehouse: "[Environment Default]"
        database: "${ev_database}"
        schema: "${ev_controls_schema}"
        targetTable: "CTRL_TEST_DQ_TESTS"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "SOR_KEY"
          - "SOR_KEY"
        - - "FILE_KEY"
          - "FILE_KEY"
        - - "PROCESS_STEP"
          - "PROCESS_STEP"
        - - "SCHEMA_NAME"
          - "SCHEMA_NAME"
        - - "TABLE_NAME"
          - "TABLE_NAME"
        - - "TEST_INDEX"
          - "TEST_INDEX"
        - - "TEST_NAME"
          - "TEST_NAME"
        - - "TEST_DESCRIPTION"
          - "TEST_DESCRIPTION"
        - - "TEST_CATEGORY"
          - "TEST_CATEGORY"
        - - "TEST_SQL_QUERY"
          - "TEST_SQL_QUERY"
        - - "RESULT_TYPE"
          - "RESULT_TYPE"
        - - "RESULT_VALUE_EXPECTED"
          - "RESULT_VALUE_EXPECTED"
        - - "ACTIVE_FLAG"
          - "ACTIVE_FLAG"
        orderBy:
        outputMode: "Truncate"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Fixed Flow:
      position:
        x: 450
        "y": 100
      tempMetlId: 1
    CTRL_TEST_DQ_TESTS:
      position:
        x: 690
        "y": 100
      tempMetlId: 2
